class SymptomAnalyzer:

    @staticmethod
    def analyze(symptoms: str):

        symptoms = symptoms.lower()

        if "chest pain" in symptoms:
            return {
                "riskLevel": "HIGH",
                "recommendation":
                    "Immediate medical attention recommended."
            }

        if "difficulty breathing" in symptoms:
            return {
                "riskLevel": "HIGH",
                "recommendation":
                    "Visit the nearest healthcare center immediately."
            }

        if "fever" in symptoms and "cough" in symptoms:
            return {
                "riskLevel": "MEDIUM",
                "recommendation":
                    "Response generated by Python AI service."
            }

        return {
            "riskLevel": "LOW",
            "recommendation":
                "Rest and monitor symptoms."
        }